## Reformat Bird Soundscapes & Training Data to Anqa

Converts a dog's breakfast of sources, annotation programs and methodologies into a cleaned and unified tabular ML-friendly data format *Anqa* with time-frequency bounding boxes and a separate file for per-recording metadata.

### Motivation & Summary

* The format should allow quality soundscapes, to be built with retention of metadata, and capability for continuous reviewing & improvement plus cropping or chunking to shorter samples as needed.  

* By making the format compatible with the model outputs, human-in-loop reviewed field data can easily contribute to improved future datasets.

* By working with randomly selected soundscapes rather than model detections or pseudolabels we avoid creating models that get increasingly biased by only learning what they already know.  

<img src="..//images/anqa_diagram.png" width="900">


The format combined with the methods in WildPyTools should support all the following:

* Create a dataset of soundscapes with a specified maximum length, in `.flac` audio format
* Keep track of any metadata available, with one row per soundscape
* T-F annotations for future processing, training pipelines, or human-in-loop continuous improvement
* Optional conversion to `.selections.txt` files for visualisation or editing in Raven
* Methods for direct reviewing and editing in a Jupyter notebook
* Models for detection of unlabelled animal sounds, or human-voice to label as a_detect or h_detect
* Convert weakly/sparsely labelled soundscapes into densely labelled soundscapes of fixed length
* Merge labels and metadata from multiple Anqa datasets into unified parent tables (with updated file paths)

### Methods

**Source Data (Labels plus corresponding .wav, .ogg or .flac files)**
* A previously compiled Anqa dataset
* Raven `.selections.txt` tab seperated tables
* A BirdCLEF - Zenodo style soundscape `.csv` tidytable with one bounding box per row, as per [here](https://zenodo.org/records/7018484)
* An existing BirdCLEF-style metadata dataframe with data such as licenses, lat, long, reviewed-by, reviewed-on, etc.
* AviaNZ (New Zealand) `.data` labels 
* Freebird (New Zealand) `.tag` xml labels

If starting a new dataset from scratch the annotation process should do the following:

* Create the metadata in `.csv`, with one row per sound recording, and the column names used here.
* Annotation should use Raven with e-bird and iNaturalist codes.
* Mark bounding boxes (frequency and time bounds) on every bird-call.
* Unidentified calls should still be boxed but labelled 'unknown'.
* One minute of annotations per recording is optimal (randomly sampled from a longer recording if need be).
* A 'Sex' column, m/f or left empty.
* A 'Rating' for label decision confidence on a scale of 0 to 1.

**Intermediate formatting step (Automated)**  

Parses the source files, and creates two dataframes:

1. Metadata, from the existing one if it exists, otherwise a new (mostly empty) one is created
2. Labels.  These will only be used from their original 'source' format, for example `.selections.txt` from Raven.

**Propose missing labels (Optional)**   

* Delete any annotations previously labelled 'h_detect' or 'a_detect'
* Run through every sample with a voice detection model and label any human voice.  Label 'h_detect'
* Run through every sample with an animal sound detection model.  Label 'a_detect'

**Crop or chunk longer recordings to a fixed maximum length (Optional)**  

Restrict each file to a maximum length (default 60 seconds) chosen from the whole with the most identified labels.  If none found then a random period will be chosen.  The point of this is to maximise the value of the labeller's time.  15 different files of one minute each is much more diversity than a single 15-minute file with same birds in the same background noise.

**Crop & randomly assemble sparsly labelled soundscapes**  

Turns a recording with only a small number of labels (and potentially many missing labels) into something closer to a strongly labelled soundscape.  Randomly sampling with replacement from the short-crops within it, and giving each crop a randomly sized buffer on either side.  Produces fixed length 'synthetic' soundscape, when none was available before.

**Save in Anqa format**  

* (Optional), re-save the recordings in `.flac` format
* Save the annotations 
* Save the metadata

**Human-in-loop editing**
* Create an updated raven dataset with `.selections.txt` files, plus `annotations` and `metadata`
* Externally review the `.selections.txt` files in Raven, then re-run the process above.
* Precedence will be given to the existing human-tagged labels over anything like automated bird or voice detection.
* Previously auto-labelled annotations will be over-written.

**Re-Running an existing Anqa Dataset**
* Change the chunk lengths, or take advantage of improved detection/cleaning.
* 'Densify' by removing long periods without labels, randomly selecting and concatenating the remainder
* Precedence given to human-tagged labels over anything like automated bird or voice detection.
* Previously auto-labelled annotations will be over-written.

### Notebook Configuration
(Adjust as needed)

In [677]:
from pathlib import Path
project_root = str(Path().resolve().parent)

In [678]:
#Note: 'anqa_destn' must differ from source directory if saving new audio files
source = 'freebird_samples'  #raven_samples, birdclef_samples, bc-zenodo_samples, avianz_samples, 
notebook_use = {'project_root': project_root,
                'source': source,
                'anqa_destn': project_root + f'/data/sample_label_formats/small_anqa_datasets/anqa_from_{source}',
                'merger_folder': project_root +  '/data/sample_label_formats/small_anqa_datasets',
                'debug': True,
                'max_seconds': 60,  #Segment and/or crop any data type to this maximum length
                'max_buffer_seconds': 1, #If cropping around bounding boxes a buffer up to this value will be added
                'crop_method': 'bbox', #'keep_all', #any of 'bbox', 'keep_all', 'random',  in future: 'max_annotations', 'max_detections'
                'padding': None, # Any of 'pad', 'noise', 'zero', None
                'save_new_flac_files': True, # If true the original source will be re-written into .flac files of length max_seconds
                'tabular_save_suffix': 'parquet' #csv
                }

### Imports

In [679]:
import os, sys
from dotenv import load_dotenv
import random
import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm
from IPython.display import display
import ipywidgets as widgets
import importlib
button = widgets.Button(description="Continue")
output = widgets.Output()

#%matplotlib widget  
torch.set_num_threads(1)

In [680]:
load_dotenv(dotenv_path = project_root + " /.env")

for p in os.getenv("PYTHONPATH", "").split(os.pathsep):
    if p:
        print(f' Adding Python path: {p}')
        sys.path.append(str(Path(p).resolve()))

 Adding Python path: ../../wildpytools/src
 Adding Python path: ./src
 Adding Python path: /home/olly/Desktop/wildpytools/src

In [681]:
#Only doing like this for convenience whilst I work on WildPyTools
import wildpytools
import wildpytools.audio as wa
importlib.reload(wa)
importlib.reload(wildpytools.io)

SourceDataLoader = wa.SourceDataLoader
ToAnqa = wa.ToAnqa
anqa_to_raven_selections = wa.anqa_to_raven_selections
save_dataframe = wildpytools.io.save_dataframe
load_dataframe = wildpytools.io.load_dataframe
merge_anqua_data = wa.merge_anqa_data

### Data Paths & Values (Simulating all possible options)

In [682]:
# These lines will over-write any existing values from the csv metadata file if it exists.  
# Comment out any items you want to leave unchanged.  
update_metadata_dict = {'collection': 'crown_jewels',
                        'secondary_labels': "['sidekick_bird']",
                        'url' : 'some_web_address',
                        'latitude': 37.0,
                        'longitude': -118.5,
                        'author' : 'Mr Bigglesworth',
                        'licence': 'some_licence',
                        #'recorded_on': 025-12-23 09:15:30, 
                        'collection' : 'birdclef_22',
                        'reviewed_on' : '2025-12-23 09:15:30',
                        'reviewed_by': 'Joe Blogs',
                        'models_used' : "['model_1']"
                        }

anqa_samples = { 'source_type': 'anqa',
              'audio_files': project_root + '/data/sample_label_formats//small_anqa_datasets/anqa_from_freebird/audio',
              'metadata_path': project_root + '/data/sample_label_formats//small_anqa_datasets/anqa_from_freebird/metadata.csv',
              'labels_path': project_root + '/data/sample_label_formats//small_anqa_datasets/anqa_from_freebird/annotations.csv',
              'naming_csv': project_root + '/data/sample_label_formats/birdclef/metadata/naming.csv',
              'naming_cols' : {'source_name': 'eBird','save_name': 'eBird'},
             }

raven_samples = {'source_type': 'raven',
                 'audio_files': project_root + '/data/sample_label_formats/raven_kokako_olly',
                 'naming_csv': project_root + '/data/experiments/exp_2/exp_2_deploy/exp_2_bird_map.csv',
                 'naming_cols' : {'source_name': 'eBird','save_name': 'eBird'},
                 'metadata_path' : None, #project_root + '/data/sample_label_formats/raven_kokako_olly/metadata.csv'
                 'metadata_dict': update_metadata_dict,  # replace with None if not updating
                }

avianz_samples = {'source_type': 'avianz',
               'audio_files': project_root + '/data/sample_label_formats/avianz_janzoon_brian',
               'naming_csv': project_root + '/data/bird_names/avianz_to_ebird.csv',
               'naming_cols' : {'source_name': 'AviaNZ','save_name': 'eBird'},
              }

freebird_samples = {'source_type': 'freebird',
                 'audio_files': project_root + '/data/sample_label_formats/freebird_tier_1',
                 'naming_csv': project_root + '/data/sample_label_formats/freebird_species_list_05112013.csv',
                 'naming_cols' : {'source_name': 'Code', 'save_name': 'eBird'},
                 'metadata_dict': update_metadata_dict
}

birdclef_samples = {
                'source_type': 'birdclef',
                'audio_files': project_root + '/data/sample_label_formats/bc25_audio_files',
                'metadata_path': project_root + '/data/sample_label_formats/birdclef/metadata/train.csv',
                'naming_csv': project_root + '/data/sample_label_formats/birdclef/metadata/naming.csv',
                'naming_cols' : {'source_name': 'eBird','save_name': 'eBird'},
                'metadata_dict': update_metadata_dict,  # replace with None if not updating
                }

#Post BirdCLEF annotated soundscapes on zenodo.org:   https://zenodo.org/search?q=birdclef&l=list&p=1&s=10&sort=bestmatch
bc_zenodo_samples = {'source_type': 'bc-zenodo',
                  'audio_files': '/home/olly/Desktop/Kaytoo/data/sample_label_formats/zenodo_birdclef/Sierra_Nevada/audio',
                  'metadata_dict': update_metadata_dict,
                  'labels_path': project_root + '/data/sample_label_formats/zenodo_birdclef/Sierra_Nevada/annotations.csv',
                  'naming_csv': project_root + '/data/sample_label_formats/birdclef/metadata/naming.csv',
                  'naming_cols' : {'source_name': 'eBird','save_name': 'eBird'},
}

data_sources = {'anqa_samples' : anqa_samples,
                'raven_samples' : raven_samples,
                'avianz_samples' : avianz_samples,
                'birdclef_samples' : birdclef_samples,
                'bc_zenodo_samples' : bc_zenodo_samples,
                'freebird_samples' : freebird_samples
                }

data_source = data_sources[notebook_use['source']]
allowed_loader_kwargs = ['metadata_path', 'metadata_dict', 'labels_path']
loader_kwargs = {
    key: val
    for key, val in data_source.items()
    if key in allowed_loader_kwargs and val is not None
}

In [683]:
class Config():
    def __init__(self, options: dict, data_sources: dict):
        self.source_data_type = data_sources[options['source']].get('source_type')
        self.debug = options['debug']
        self.max_seconds = options['max_seconds']
        self.crop_method = options['crop_method']
        self.padding = options['padding']
        self.save_new_flac_files = options['save_new_flac_files']
        self.save_raven_selections = False  # User must manually change at end of the notebook if wanted
        self.source_name = self.SAVE_NAME = None
        _naming_cols = data_sources[options['source']].get('naming_cols')
        if _naming_cols is not None:
            self.source_name = _naming_cols.get('source_name')
            self.save_name = _naming_cols.get('save_name')


class FilePaths():
    def __init__(self, notebook_use: dict, data_sources: dict):
        _source = notebook_use['source']
        _tabular_save_suffix = notebook_use['tabular_save_suffix']
        _source_cfg = data_sources[_source]
        _metadata = _source_cfg.get('metadata_path')
        _naming = _source_cfg.get('naming_csv')
        _annotations = _source_cfg.get('labels_path')
        
        self.audio_files = Path(data_sources[_source]['audio_files'])
        self.metadata = Path(_metadata) if _metadata is not None else None
        self.naming_csv = Path(_naming) if _naming is not None else None
        self.annotation_src = Path(_annotations) if _annotations is not None else None

        # Output directory (ensure it exists)
        self.anqa_destn = Path(notebook_use.get('anqa_destn'))
        self.anqa_destn.mkdir(parents=True, exist_ok=True)
        self.annotations_destn = self.anqa_destn / f'annotations.{_tabular_save_suffix}'
        self.metadata_destn = self.anqa_destn / f'metadata.{_tabular_save_suffix}'
        self.multi_anqa_fldr = notebook_use['merger_folder']

config = Config(notebook_use, data_sources)
paths = FilePaths(notebook_use, data_sources)

In [684]:
paths.metadata

In [685]:
if paths.metadata:
    testing = pd.read_csv(paths.metadata)
    display(testing.head(3))

In [686]:
if paths.annotation_src:
    testing = pd.read_csv(paths.annotation_src)
    display(testing.head(3))

In [687]:
class VoiceDetector():
    def __init__(self, chunk_len, threshold=0.1, no_voice=0, voice=20):
        model, (get_speech_timestamps, _, read_audio, _, _) = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                                                                 model='silero_vad', verbose=False)
        self.model=model
        self.chunk_len=chunk_len
        self.threshold=threshold
        self.get_stamps = get_speech_timestamps

    def detect(self, np_wav):
        speech_timestamps = self.get_stamps(torch.Tensor(np_wav), self.model, threshold=self.threshold)
        voice_detect = np.zeros_like(np_wav)
        for st in speech_timestamps:
            voice_detect[st['start']: st['end']] = 20
    
        #downsample to match the power plot axis
        voice_detect = np.pad(voice_detect, 
                            (0, int(np.ceil(len(voice_detect) / self.chunk_len) * self.chunk_len - len(voice_detect))))
        voice_detect = voice_detect.reshape((-1, self.chunk_len)).max(axis=1)  # Use max to preserve speech detection
        return voice_detect
    
def calc_signal_pwr(wav, chunk_len, sr=32000):
    power = wav ** 2 
    power = np.pad(power, (0, int(np.ceil(len(power) / chunk_len) * chunk_len - len(power))))
    power = power.reshape((-1, chunk_len)).sum(axis=1)
    return power


def detect_voice(labels: pd.DataFrame,
                 metadata: pd.DataFrame,
                 threshold: float = 0.5,
                 ):
    """Run a voice detection model over the spectrogram to try and locate any human-voice

    Args:
        df_labels (_type_): _description_
        df_meta (_type_): _description_
    """
    return labels, metadata


def detect_animal_sound(labels: pd.DataFrame,
                        metadata: pd.DataFrame,
                        ):

    """Run an object detection model over spectrograms to propose any missing labels for bird or animal sounds

    Args:
        df_labels (_type_): _description_
        df_meta (_type_): _description_
    """
    return labels, metadata

## Load source data

In [688]:
if paths.metadata is not None:
    meta_df = pd.read_csv(paths.metadata)
    display(meta_df.head(3))
    display(f'The metadata dataframe has length {len(meta_df)}')

Setup mapping between the source data and the new dataset

In [689]:
if paths.naming_csv is not None:
    source_names = pd.read_csv(paths.naming_csv)
    source_col = config.source_name
    save_col = config.save_name
    save_name_map = dict(zip(source_names.loc[:, source_col], source_names.loc[:, save_col]))
    display(source_names.head(3))

   Code              CommonName    eBird            ScientificName
0     1    Antipodean Albatross  antalb1     Diomedea antipodensis
1     2    Antipodean Albatross  antalb1     Diomedea antipodensis
2     3  Black-browed Albatross   bkbalb  Thalassarche melanophris

In [690]:
paths.audio_files

PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1')

In [691]:
dataset_loader = SourceDataLoader(source_type = config.source_data_type,
                                  rename_map = save_name_map,
                                  )
print(f'Loading source data of the type {config.source_data_type}')
print(loader_kwargs)

df_label, df_meta = dataset_loader.load_data(paths.audio_files, **loader_kwargs)

Loading source data of the type freebird
{'metadata_dict': {'collection': 'birdclef_22', 'secondary_labels': "['sidekick_bird']", 'url': 'some_web_address', 'latitude': 37.0, 'longitude': -118.5, 'author': 'Mr Bigglesworth', 'licence': 'some_licence', 'reviewed_on': '2025-12-23 09:15:30', 'reviewed_by': 'Joe Blogs', 'models_used': "['model_1']"}}
These are the label cols: ['Filename', 'Start Time (s)', 'End Time (s)', 'Low Freq (Hz)', 'High Freq (Hz)', 'Label', 'Type', 'Sex', 'Score', 'Delta Time (s)', 'Delta Freq (Hz)', 'Avg Power Density (dB FS/Hz)', 'Filepath']
These are the metadata cols: ['filename', 'collection', 'secondary_labels', 'url', 'latitude', 'longitude', 'author', 'license', 'recorded_on', 'reviewed_by', 'reviewed_on', 'source_filename', 'source_start_s', 'source_end_s', 'models_used']
This is the rename map: {1: 'antalb1', 2: 'antalb1', 3: 'bkbalb', 4: 'bkbalb2', 5: 'shyalb2', 6: 'wanalb4', 7: 'yenalb3', 8: 'limalb1', 9: 'bulalb2', 10: 'royalb1', 11: 'royalb3', 12: 'whcalb1', 13: 'salalb1', 14: 'bulalb2', 15: 'royalb2', 16: 'wanalb1', 17: 'nezbel1', 18: 'nezbel1', 19: 'nezbel1', 20: 'ausbit1', 21: 'eurbla', 22: 'masboo', 23: 'revbul', 24: 'cirbun1', 25: 'comcha', 26: 'redjun1', 27: 'chukar', 28: 'succoc', 29: 'eurcoo', 30: 'baicra4', 31: 'spocra2', 32: 'spocra1', 33: 'pipipi1', 34: 'bicpen1', 35: 'lotkoe1', 36: 'shbcuc1', 37: 'faecur', 38: 'nezgre1', 39: 'dollar1', 40: 'rebdot1', 41: 'dobplo1', 42: 'dobplo1', 43: 'blfdot1', 44: 'grsplo', 45: 'lessap2', 46: 'rebdot2', 47: 'rebdot3', 48: 'barpar2', 49: 'basdov1', 50: 'spodov', 51: 'spodov', 52: 'bluduc1', 53: 'pabduc1', 54: 'x00458', 55: 'x00458', 56: 'mallar3', 57: 'dunnoc1', 58: 'categr1', 59: 'categr2', 60: 'litegr', 61: 'badbird', 62: 'nezfal1', 63: 'nezfan1', 64: 'nezfan1', 65: 'nezfan1', 66: 'nezfan1', 67: 'fernbi1', 68: 'fernbi1', 69: 'fernbi1', 70: 'fernbi3', 71: 'fernbi1', 72: 'fernbi1', 73: 'badbird', 74: 'souful1', 75: 'galah', 76: 'ausgan1', 77: 'y00228', 78: 'bktgod3', 79: 'batgod2', 80: 'hudgod', 81: 'godwit1', 82: 'eurgol', 83: 'cangoo', 84: 'cabgoo1', 85: 'gragoo1', 86: 'grcgre1', 87: 'litgre1', 88: 'hohgre1', 89: 'eurgre1', 90: 'comgre', 91: 'helgui6', 92: 'blbgul1', 93: 'rebgul1', 94: 'kelgul', 95: 'larus', 96: 'swahar1', 97: 'runher1', 98: 'pacreh1', 99: 'greegr', 100: 'whfher1', 101: 'gloibi', 102: 'nezkak1', 103: 'nezkak1', 104: 'nezkak1', 105: 'kakapo2', 106: 'kea1', 107: 'auskes1', 108: 'sackin1', 109: 'sobkiw2', 110: 'grskiw1', 111: 'liskiw1', 112: 'nibkiw1', 113: 'okbkiw1', 114: 'kiwi1', 115: 'sobkiw2', 116: 'sobkiw2', 117: 'grekno', 118: 'redkno', 119: 'kokako3', 120: 'laukoo1', 121: 'railor4', 122: 'ausmag2', 123: 'tremar2', 124: 'yellow3', 125: 'morepo2', 126: 'commyn', 127: 'grynod1', 128: 'brnowl', 129: 'litowl1', 130: 'chaoys1', 131: 'soioys1', 132: 'oyster1', 133: 'varoys1', 134: 'antpar1', 135: 'refpar4', 136: 'chipar1', 137: 'refpar4', 138: 'malpar2', 139: 'refpar4', 140: 'reipar1', 141: 'parake', 142: 'yefpar3', 143: 'relpar1', 144: 'rocpar2', 145: 'compea', 146: 'auspel1', 147: 'rocpen3', 148: 'bicpen1', 149: 'fiopen1', 150: 'litpen1', 151: 'macpen1', 152: 'snapen1', 153: 'yeepen1', 154: 'parpet1', 155: 'bbspet1', 156: 'bkwpet', 157: 'blupet1', 158: 'cappet', 159: 'chapet1', 160: 'codpet1', 161: 'coopet', 162: 'badbird', 163: 'snopet1', 164: 'grapet', 165: 'gybstp1', 166: 'grwpet2', 167: 'kerpet', 168: 'nezstp1', 169: 'snopet1', 170: 'motpet', 171: 'codpet1', 172: 'norgip1', 173: 'nezstp1', 174: 'wfspet', 175: 'badbird', 176: 'solpet1', 177: 'pycpet1', 178: 'cappet', 179: 'snopet1', 180: 'soppet1', 181: 'sgdpet1', 182: 'codpet1', 183: 'angpet1', 184: 'badbird', 185: 'codpet1', 186: 'wespet1', 187: 'whcpet1', 188: 'whhpet1', 189: 'whnpet', 190: 'wispet', 191: 'rinphe1', 192: 'nezpig3', 193: 'nezpig2', 194: 'rocpig', 195: 'auspip3', 196: 'auspip3', 197: 'auspip3', 198: 'auspip3', 199: 'bkbplo', 200: 'pagplo', 201: 'shoplo1', 202: 'maslap1', 203: 'dovpri1', 204: 'dovpri1', 205: 'brbpri1', 206: 'fulpri1', 207: 'faipri1', 208: 'fulpri1', 209: 'fulpri1', 210: 'salpri2', 211: 'badbird', 212: 'slbpri1', 213: 'purswa6', 214: 'broqua1', 215: 'norbob', 216: 'calqua', 217: 'auirai1', 218: 'bubrai1', 219: 'comred', 220: 'riflem1', 221: 'riflem1', 222: 'riflem1', 223: 'charob1', 224: 'nezrob2', 225: 'nezrob2', 226: 'nezrob3', 227: 'nezrob3', 228: 'rook1', 229: 'criros2', 230: 'easros1', 231: 'badbird', 232: 'saddle2', 233: 'saddle3', 234: 'sander', 235: 'cursan', 236: 'brbsan', 237: 'marsan', 238: 'pecsan', 239: 'shtsan', 240: 'tersan', 241: 'gyttat1', 242: 'nezsca1', 243: 'auisha1', 244: 'grecor', 245: 'sposha1', 246: 'boisha1', 247: 'caisha2', 248: 'chisha1', 249: 'lipcor1', 250: 'libcor1', 251: 'rofsha1', 252: 'piecor1', 253: 'piisha1', 254: 'sposha1', 255: 'badbird', 256: 'brosha1', 257: 'bulshe', 258: 'flfshe', 259: 'flushe1', 260: 'hutshe1', 261: 'litshe8', 262: 'litshe8', 263: 'litshe8', 264: 'shtshe', 265: 'sooshe', 266: 'badbird', 267: 'litshe4', 268: 'wetshe', 269: 'ausshe1', 270: 'parshe1', 271: 'aussho1', 272: 'silver3', 273: 'sopsku1', 274: 'parjae', 275: 'brnsku3', 276: 'pomjae', 277: 'badbird', 278: 'brnsku3', 279: 'skylar', 280: 'subsni1', 281: 'subsni1', 282: 'subsni1', 283: 'chisni1', 284: 'snisni1', 285: 'houspa', 286: 'royspo1', 287: 'eursta', 288: 'blasti1', 289: 'piesti1', 290: 'rensti', 291: 'stitch1', 292: 'welswa1', 293: 'blkswa', 294: 'mutswa', 295: 'whtnee', 296: 'magpet1', 297: 'takahe3', 298: 'gyttat1', 299: 'wantat1', 300: 'auitea1', 301: 'brotea1', 302: 'caitea1', 303: 'chetea1', 304: 'gretea1', 305: 'antter1', 306: 'arcter', 307: 'blfter1', 308: 'caster1', 309: 'comter', 310: 'litter1', 311: 'faiter2', 312: 'gubter2', 313: 'sooter1', 314: 'whfter1', 315: 'sonthr1', 316: 'tomtit1', 317: 'tomtit1', 318: 'tomtit1', 319: 'tomtit1', 320: 'tomtit1', 321: 'tomtit1', 322: 'ettro', 323: 'tui1', 324: 'tui1', 325: 'wiltur', 326: 'rudtur', 327: 'chiger2', 328: 'gryger1', 329: 'weka1', 330: 'weka1', 331: 'weka1', 332: 'weka1', 333: 'weka1', 334: 'whimbr', 335: 'whimbr', 336: 'whimbr', 337: 'litcur', 338: 'whiteh1', 339: 'soiwre1', 340: 'wrybil1', 341: 'yellow2', 342: 'spybird', 343: 'spybird', 344: 'spybird', 345: 'spybird', 346: 'spybird', 347: 'spybird', 348: 'spybird', 349: 'spybird', 350: 'spybird', 351: 'spybird', 352: 'spybird'}
This is the audio dir /home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1

1792it [00:00, 222122.84it/s]

These are the paired values {'AA144_BIRA_130225_091420': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AA144_BIRA_130225_091420.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AA144_BIRA_130225_091420.tag')}, 'AB140_BIRX_130313_104353': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB140_BIRX_130313_104353.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB140_BIRX_130313_104353.tag')}, 'AA144_BIRD_130225_105848': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AA144_BIRD_130225_105848.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AA144_BIRD_130225_105848.tag')}, 'AB140_BIRA_130314_091420': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB140_BIRA_130314_091420.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB140_BIRA_130314_091420.tag')}, 'AB142_BIRX_130227_084430': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB142_BIRX_130227_084430.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB142_BIRX_130227_084430.tag')}, 'AC149_BIRD_121107_124316': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AC149_BIRD_121107_124316.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AC149_BIRD_121107_124316.tag')}, 'AC149_BIRD_121107_122821': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AC149_BIRD_121107_122821.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AC149_BIRD_121107_122821.tag')}, 'AB140_BIRM_130313_101402': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB140_BIRM_130313_101402.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB140_BIRM_130313_101402.tag')}, 'AB140_BIRX_130313_105848': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB140_BIRX_130313_105848.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB140_BIRX_130313_105848.tag')}, 'AB140_BIRP_130313_114334': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB140_BIRP_130313_114334.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB140_BIRP_130313_114334.tag')}, 'AC149_BIRA_121107_121334': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AC149_BIRA_121107_121334.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AC149_BIRA_121107_121334.tag')}, 'AB142_BIRP_130227_091420': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB142_BIRP_130227_091420.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB142_BIRP_130227_091420.tag')}, 'AB142_BIRD_130228_095907': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB142_BIRD_130228_095907.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB142_BIRD_130228_095907.tag')}, 'AB140_BIRD_130313_114334': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AB140_BIRD_130313_114334.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AB140_BIRD_130313_114334.tag')}, 'AA144_BIRP_130226_121325': {'audio': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AA144_BIRP_130226_121325.wav'), 'labels': PosixPath('/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/.session/AA144_BIRP_130226_121325.tag')}}

100%|██████████| 15/15 [00:00<00:00, 1943.61it/s]
Exception "['Type', 'Sex', 'Score', 'Delta Time (s)', 'Delta Freq (Hz)', 'Avg Power Density (dB FS/Hz)'] not in index" combining or filtering columns from 7 dataframes

Low: 3625.0, High: 4937.5
Low: 3625.0, High: 4937.5
Low: 3312.5, High: 5812.5
Low: 3312.5, High: 5812.5
Low: 2906.25, High: 5875.0
Low: 2906.25, High: 5875.0
Low: 3250.0, High: 4750.0
Low: 3250.0, High: 4750.0
Low: 3281.25, High: 4562.5
Low: 3281.25, High: 4562.5
Low: 3656.25, High: 5812.5
Low: 3656.25, High: 5812.5
Low: 5218.75, High: 7437.5
Low: 5218.75, High: 7437.5
Low: 4281.25, High: 5875.0
Low: 4281.25, High: 5875.0
Low: 3687.5, High: 4687.5
Low: 3687.5, High: 4687.5
Low: 5312.5, High: 7250.0
Low: 5312.5, High: 7250.0
Low: 3843.75, High: 4468.75
Low: 3843.75, High: 4468.75
Low: 3750.0, High: 5718.75
Low: 3750.0, High: 5718.75
Low: 5468.75, High: 7437.5
Low: 5468.75, High: 7437.5
Low: 3781.25, High: 4531.25
Low: 3781.25, High: 4531.25
Low: 3281.25, High: 5781.25
Low: 3281.25, High: 5781.25
Low: 3218.75, High: 5093.75
Low: 3218.75, High: 5093.75
Low: 3593.75, High: 4562.5
Low: 3593.75, High: 4562.5
Low: 5500.0, High: 7312.5
Low: 5500.0, High: 7312.5
Low: 6062.5, High: 7906.25
Low: 6062.5, High: 7906.25
Low: 2968.75, High: 5312.5
Low: 2968.75, High: 5312.5
Low: 3812.5, High: 4593.75
Low: 3812.5, High: 4593.75
Low: 3437.5, High: 5281.25
Low: 3437.5, High: 5281.25
Low: 3687.5, High: 4656.25
Low: 3687.5, High: 4656.25
Low: 3281.25, High: 5125.0
Low: 3281.25, High: 5125.0
Low: 3156.25, High: 5593.75
Low: 3156.25, High: 5593.75
Low: 3000.0, High: 5718.75
Low: 3000.0, High: 5718.75
Low: 2906.25, High: 5687.5
Low: 2906.25, High: 5687.5
Low: 4562.5, High: 6406.25
Low: 4562.5, High: 6406.25
Low: 2843.75, High: 5468.75
Low: 2843.75, High: 5468.75
Low: 2937.5, High: 5218.75
Low: 2937.5, High: 5218.75
Low: 4812.5, High: 6187.5
Low: 4812.5, High: 6187.5
Low: 3125.0, High: 5375.0
Low: 3125.0, High: 5375.0
Low: 2875.0, High: 6062.5
Low: 2875.0, High: 6062.5
Low: 2875.0, High: 5781.25
Low: 2875.0, High: 5781.25
Low: 2937.5, High: 5687.5
Low: 2937.5, High: 5687.5
Low: 2968.75, High: 5625.0
Low: 2968.75, High: 5625.0
Low: 3031.25, High: 4375.0
Low: 3031.25, High: 4375.0
Low: 2812.5, High: 5687.5
Low: 2812.5, High: 5687.5
Low: 2750.0, High: 5500.0
Low: 2750.0, High: 5500.0
Low: 2750.0, High: 6375.0
Low: 2750.0, High: 6375.0
Low: 2875.0, High: 5968.75
Low: 2875.0, High: 5968.75
Low: 2781.25, High: 5718.75
Low: 2781.25, High: 5718.75
Low: 2687.5, High: 5718.75
Low: 2687.5, High: 5718.75
Low: 2843.75, High: 5781.25
Low: 2843.75, High: 5781.25
Low: 2687.5, High: 5656.25
Low: 2687.5, High: 5656.25
Low: 2718.75, High: 6250.0
Low: 2718.75, High: 6250.0
Low: 2718.75, High: 5875.0
Low: 2718.75, High: 5875.0
Low: 5906.25, High: 8406.25
Low: 5906.25, High: 8406.25
Low: 6125.0, High: 8500.0
Low: 6125.0, High: 8500.0
Low: 6156.25, High: 8531.25
Low: 6156.25, High: 8531.25
Low: 5937.5, High: 8000.0
Low: 5937.5, High: 8000.0
Low: 3187.5, High: 6250.0
Low: 3187.5, High: 6250.0
Low: 6312.5, High: 7718.75
Low: 6312.5, High: 7718.75
Low: 3156.25, High: 6187.5
Low: 3156.25, High: 6187.5
Low: 3031.25, High: 5250.0
Low: 3031.25, High: 5250.0
Low: 2343.75, High: 6156.25
Low: 2343.75, High: 6156.25
Low: 5968.75, High: 8250.0
Low: 5968.75, High: 8250.0
Low: 6343.75, High: 7968.75
Low: 6343.75, High: 7968.75
Low: 5437.5, High: 7312.5
Low: 5437.5, High: 7312.5
Low: 5593.75, High: 7687.5
Low: 5593.75, High: 7687.5
Low: 5750.0, High: 7750.0
Low: 5750.0, High: 7750.0
Low: 6312.5, High: 7906.25
Low: 6312.5, High: 7906.25
Low: 3656.25, High: 5062.5
Low: 3656.25, High: 5062.5
Low: 3531.25, High: 5093.75
Low: 3531.25, High: 5093.75
Low: 3468.75, High: 7156.25
Low: 3468.75, High: 7156.25
Low: 2812.5, High: 4625.0
Low: 2812.5, High: 4625.0
Low: 5812.5, High: 8031.25
Low: 5812.5, High: 8031.25
Low: 2781.25, High: 4562.5
Low: 2781.25, High: 4562.5
Low: 2625.0, High: 7406.25
Low: 2625.0, High: 7406.25
Low: 6218.75, High: 7437.5
Low: 6218.75, High: 7437.5
Low: 2531.25, High: 7687.5
Low: 2531.25, High: 7687.5
Low: 2968.75, High: 5250.0
Low: 2968.75, High: 5250.0
Low: 2968.75, High: 5468.75
Low: 2968.75, High: 5468.75
Low: 2812.5, High: 5250.0
Low: 2812.5, High: 5250.0
Low: 2812.5, High: 8000.0
Low: 2812.5, High: 8000.0
Low: 3562.5, High: 5312.5
Low: 3562.5, High: 5312.5
Low: 3437.5, High: 5718.75
Low: 3437.5, High: 5718.75
Low: 4656.25, High: 8312.5
Low: 4656.25, High: 8312.5
Low: 2250.0, High: 6312.5
Low: 2250.0, High: 6312.5
Low: 3406.25, High: 5375.0
Low: 3406.25, High: 5375.0
Low: 7031.25, High: 8500.0
Low: 7031.25, High: 8500.0
Low: 2125.0, High: 8031.25
Low: 2125.0, High: 8031.25
Low: 2468.75, High: 8093.75
Low: 2468.75, High: 8093.75
Low: 1906.25, High: 7968.75
Low: 1906.25, High: 7968.75
Low: 2375.0, High: 7812.5
Low: 2375.0, High: 7812.5
Low: 1812.5, High: 8125.0
Low: 1812.5, High: 8125.0
Low: 2218.75, High: 8093.75
Low: 2218.75, High: 8093.75
Low: 2250.0, High: 8156.25
Low: 2250.0, High: 8156.25
Low: 2031.25, High: 7468.75
Low: 2031.25, High: 7468.75
Low: 2187.5, High: 7437.5
Low: 2187.5, High: 7437.5
Low: 2843.75, High: 7468.75
Low: 2843.75, High: 7468.75
Low: 0.0, High: 1062.5
Low: 0.0, High: 1062.5
Low: 2500.0, High: 7812.5
Low: 2500.0, High: 7812.5
Low: 2781.25, High: 7562.5
Low: 2781.25, High: 7562.5
Low: 2500.0, High: 7406.25
Low: 2500.0, High: 7406.25
Low: 2250.0, High: 6343.75
Low: 2250.0, High: 6343.75
Low: 2250.0, High: 6468.75
Low: 2250.0, High: 6468.75
Low: 2125.0, High: 5843.75
Low: 2125.0, High: 5843.75
Low: -31.25, High: 1031.25
[Info]: The file troubling_subfolder/AC149_BIRD_121107_124316.wav had a frequency value < 0kHz
Low: 2250.0, High: 6781.25
Low: 2250.0, High: 6781.25
Low: 2906.25, High: 6406.25
Low: 2906.25, High: 6406.25
Low: 2843.75, High: 6062.5
Low: 2843.75, High: 6062.5
Low: 3250.0, High: 6593.75
Low: 3250.0, High: 6593.75
Low: 2468.75, High: 6062.5
Low: 2468.75, High: 6062.5
Low: 2593.75, High: 6187.5
Low: 2593.75, High: 6187.5
Low: 2593.75, High: 5625.0
Low: 2593.75, High: 5625.0
Low: 4093.75, High: 8062.5
Low: 4093.75, High: 8062.5
Low: 2906.25, High: 6062.5
Low: 2906.25, High: 6062.5
Low: 3000.0, High: 7000.0
Low: 3000.0, High: 7000.0
Low: 1875.0, High: 6812.5
Low: 1875.0, High: 6812.5
Low: 2906.25, High: 7062.5
Low: 2906.25, High: 7062.5
Low: 2281.25, High: 7187.5
Low: 2281.25, High: 7187.5
Low: 2875.0, High: 6187.5
Low: 2875.0, High: 6187.5
Low: 2062.5, High: 5656.25
Low: 2062.5, High: 5656.25
Low: 2093.75, High: 7125.0
Low: 2093.75, High: 7125.0
Low: 5156.25, High: 6406.25
Low: 5156.25, High: 6406.25
Low: 437.5, High: 6250.0
Low: 437.5, High: 6250.0
Low: 1031.25, High: 6000.0
Low: 1031.25, High: 6000.0
Low: 2125.0, High: 3656.25
Low: 2125.0, High: 3656.25
Low: 1250.0, High: 5093.75
Low: 1250.0, High: 5093.75
Low: 2937.5, High: 5687.5
Low: 2937.5, High: 5687.5
Low: 2593.75, High: 3781.25
Low: 2593.75, High: 3781.25
Low: 2968.75, High: 4906.25
Low: 2968.75, High: 4906.25
Low: 2218.75, High: 4750.0
Low: 2218.75, High: 4750.0
Low: 2250.0, High: 3875.0
Low: 2250.0, High: 3875.0
Low: 2750.0, High: 6593.75
Low: 2750.0, High: 6593.75
Low: 3031.25, High: 4468.75
Low: 3031.25, High: 4468.75
Low: 2062.5, High: 3812.5
Low: 2062.5, High: 3812.5
Low: 2562.5, High: 3968.75
Low: 2562.5, High: 3968.75
Low: 2750.0, High: 3812.5
Low: 2750.0, High: 3812.5
Low: 3031.25, High: 5750.0
Low: 3031.25, High: 5750.0
Low: 1843.75, High: 4281.25
Low: 1843.75, High: 4281.25
Low: 2843.75, High: 4468.75
Low: 2843.75, High: 4468.75
Low: 3125.0, High: 5593.75
Low: 3125.0, High: 5593.75
Low: 3062.5, High: 5406.25
Low: 3062.5, High: 5406.25
Low: 1781.25, High: 5156.25
Low: 1781.25, High: 5156.25
Low: 3031.25, High: 5437.5
Low: 3031.25, High: 5437.5
Low: 3218.75, High: 4937.5
Low: 3218.75, High: 4937.5
Low: 3062.5, High: 5000.0
Low: 3062.5, High: 5000.0
Low: 3531.25, High: 5562.5
Low: 3531.25, High: 5562.5
Low: 2062.5, High: 5375.0
Low: 2062.5, High: 5375.0
Low: 1281.25, High: 3468.75
Low: 1281.25, High: 3468.75
Low: 3000.0, High: 5593.75
Low: 3000.0, High: 5593.75
Low: 1625.0, High: 3531.25
Low: 1625.0, High: 3531.25
Low: 2843.75, High: 4906.25
Low: 2843.75, High: 4906.25
Low: 1906.25, High: 5250.0
Low: 1906.25, High: 5250.0
Low: 2187.5, High: 3968.75
Low: 2187.5, High: 3968.75
Low: 2125.0, High: 3968.75
Low: 2125.0, High: 3968.75
Low: 2187.5, High: 3531.25
Low: 2187.5, High: 3531.25
Low: 2437.5, High: 4906.25
Low: 2437.5, High: 4906.25
Low: 2781.25, High: 4281.25
Low: 2781.25, High: 4281.25
Low: 1000.0, High: 2062.5
Low: 1000.0, High: 2062.5
Low: 1625.0, High: 4718.75
Low: 1625.0, High: 4718.75
Low: 2437.5, High: 5218.75
Low: 2437.5, High: 5218.75
Low: 2062.5, High: 6531.25
Low: 2062.5, High: 6531.25
Low: 2093.75, High: 4718.75
Low: 2093.75, High: 4718.75
Low: 3718.75, High: 4906.25
Low: 3718.75, High: 4906.25
Low: 3406.25, High: 4468.75
Low: 3406.25, High: 4468.75
Low: 2843.75, High: 4843.75
Low: 2843.75, High: 4843.75
Low: 3343.75, High: 5218.75
Low: 3343.75, High: 5218.75
Low: 2062.5, High: 7687.5
Low: 2062.5, High: 7687.5
Low: 3218.75, High: 6281.25
Low: 3218.75, High: 6281.25
Low: 2593.75, High: 4781.25
Low: 2593.75, High: 4781.25
Low: 2625.0, High: 5187.5
Low: 2625.0, High: 5187.5
Low: 2406.25, High: 7156.25
Low: 2406.25, High: 7156.25
Low: 2625.0, High: 7718.75
Low: 2625.0, High: 7718.75
Low: 2812.5, High: 4750.0
Low: 2812.5, High: 4750.0
Low: 2750.0, High: 4843.75
Low: 2750.0, High: 4843.75
Low: 2437.5, High: 6625.0
Low: 2437.5, High: 6625.0
Low: 7562.5, High: 9843.75
Low: 7562.5, High: 9843.75
Low: 3125.0, High: 5906.25
Low: 3125.0, High: 5906.25
Low: 3125.0, High: 5593.75
Low: 3125.0, High: 5593.75
Low: 2187.5, High: 4781.25
Low: 2187.5, High: 4781.25
Low: 2875.0, High: 5468.75
Low: 2875.0, High: 5468.75
Low: 2843.75, High: 5781.25
Low: 2843.75, High: 5781.25
Low: 2625.0, High: 6718.75
Low: 2625.0, High: 6718.75
Low: 2968.75, High: 6125.0
Low: 2968.75, High: 6125.0
Low: 2500.0, High: 5437.5
Low: 2500.0, High: 5437.5
Low: 2187.5, High: 6031.25
Low: 2187.5, High: 6031.25
Low: 2687.5, High: 5906.25
Low: 2687.5, High: 5906.25
Low: 2968.75, High: 5781.25
Low: 2968.75, High: 5781.25
Low: 2718.75, High: 6062.5
Low: 2718.75, High: 6062.5
Low: 2937.5, High: 5562.5
Low: 2937.5, High: 5562.5
Low: 1750.0, High: 6406.25
Low: 1750.0, High: 6406.25
Low: 1343.75, High: 7687.5
Low: 1343.75, High: 7687.5
Low: 2625.0, High: 6406.25
Low: 2625.0, High: 6406.25
Low: 2375.0, High: 6062.5
Low: 2375.0, High: 6062.5
Low: 2187.5, High: 7750.0
Low: 2187.5, High: 7750.0
Low: 2468.75, High: 8125.0
Low: 2468.75, High: 8125.0
Low: 2000.0, High: 5437.5
Low: 2000.0, High: 5437.5
Low: 1500.0, High: 5343.75
Low: 1500.0, High: 5343.75
Low: 1343.75, High: 4625.0
Low: 1343.75, High: 4625.0
Low: 2781.25, High: 5468.75
Low: 2781.25, High: 5468.75

Note that we're ignoring any 'secondary' labels at this point, but if there is a primary/secondary labelling it is retained in the metadata.  In the case of AviaNZ-sourced data any multi-bird lists have been labelled 'unknown'

In [692]:
df_label.head(3)

,Filename,Start Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),Label,Type,Sex,Score,Delta Time (s),Delta Freq (Hz),Avg Power Density (dB FS/Hz),Filepath
0,troubling_subfolder/AA144_BIRA_130225_091420.wav,423.9,425.0,3625.00,4937.5,snapen1,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AA144_BIRA_130225_091420.wav
1,troubling_subfolder/AA144_BIRA_130225_091420.wav,427.6,429.6,3312.50,5812.5,kokako3,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AA144_BIRA_130225_091420.wav
2,troubling_subfolder/AA144_BIRA_130225_091420.wav,430.5,431.4,2906.25,5875.0,kokako3,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,/home/olly/Desktop/Kaytoo/data/sample_label_formats/freebird_tier_1/troubling_subfolder/AA144_BIRA_130225_091420.wav

In [693]:
if config.debug:
    df_label = df_label.head(40)
    df_meta = df_meta.head(40)

In [694]:
df_meta.head(3)

,filename,collection,secondary_labels,url,latitude,longitude,author,license,recorded_on,reviewed_by,reviewed_on,source_filename,source_start_s,source_end_s,models_used
0,troubling_subfolder/AA144_BIRA_130225_091420.wav,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,NaT,Joe Blogs,2025-12-23 09:15:30,troubling_subfolder/AA144_BIRA_130225_091420.wav,NaN,NaN,['model_1']
1,troubling_subfolder/AA144_BIRD_130225_105848.wav,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,NaT,Joe Blogs,2025-12-23 09:15:30,troubling_subfolder/AA144_BIRD_130225_105848.wav,NaN,NaN,['model_1']
2,troubling_subfolder/AC149_BIRD_121107_124316.wav,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,NaT,Joe Blogs,2025-12-23 09:15:30,troubling_subfolder/AC149_BIRD_121107_124316.wav,NaN,NaN,['model_1']

In [695]:
df_meta.shape

(7, 15)

## Pre-filter the audio files

* Voice detection
* Bird-call detection

In [696]:
df_label, df_meta = detect_voice(df_label, df_meta, threshold=False)
df_label, df_meta = detect_animal_sound(df_label, df_meta)

## Convert the source data to Anqa Format

In [697]:
converter = ToAnqa(source_dir=paths.audio_files,
                   destn_dir=paths.anqa_destn,
                   name_map=save_name_map,
                   save_audio=config.save_new_flac_files,
                   max_seconds=config.max_seconds,
                   end_padding=config.padding,
                   crop_method=config.crop_method,
                   n_jobs=4,
                   min_hz=200,
                   max_hz=15000,
                   )

df_labels, df_meta = converter.convert_all(df_label, df_meta)

Converting recordings: 100%|██████████| 1/1 [00:00<00:00, 1885.93it/s]

In [698]:
pd.set_option("display.max_colwidth", None)

In [699]:
df_labels.head(3)

,Filename,Start Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),Label,Indv ID,Type,Sex,Score,Life Stage,Delta Time (s),Delta Freq (Hz),Avg Power Density (dB FS/Hz)
0,audio/AA144_BIRA_130225_0914200_from_423.flac,0.5,1.6,3625.0,4938.0,snapen1,<NA>,<NA>,<NA>,NaN,<NA>,1.1,1312.0,-53.0
1,audio/AA144_BIRA_130225_0914201_from_427.flac,0.5,2.5,3312.0,5812.0,kokako3,<NA>,<NA>,<NA>,NaN,<NA>,2.0,2500.0,-56.8
2,audio/AA144_BIRA_130225_0914202_from_430.flac,0.5,1.4,2906.0,5875.0,kokako3,<NA>,<NA>,<NA>,NaN,<NA>,0.9,2969.0,-59.1

In [700]:
df_meta.head(3)

,filename,collection,secondary_labels,url,latitude,longitude,author,license,recorded_on,reviewed_by,reviewed_on,source_filename,source_start_s,source_end_s,models_used
0,audio/AA144_BIRA_130225_0914200_from_423.flac,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,NaN,Joe Blogs,2025-12-23 09:15:30,troubling_subfolder/AA144_BIRA_130225_091420.wav,423.4,425.5,['model_1']
1,audio/AA144_BIRA_130225_0914201_from_427.flac,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,NaN,Joe Blogs,2025-12-23 09:15:30,troubling_subfolder/AA144_BIRA_130225_091420.wav,427.1,430.1,['model_1']
2,audio/AA144_BIRA_130225_0914202_from_430.flac,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,NaN,Joe Blogs,2025-12-23 09:15:30,troubling_subfolder/AA144_BIRA_130225_091420.wav,430.0,431.9,['model_1']

In [701]:
dupe_filenames = df_meta[df_meta['filename'].duplicated(keep=False)]
dupe_filenames

Empty DataFrame
Columns: [filename, collection, secondary_labels, url, latitude, longitude, author, license, recorded_on, reviewed_by, reviewed_on, source_filename, source_start_s, source_end_s, models_used]
Index: []

In [702]:
save_dataframe(df_meta, paths.metadata_destn, index=False)
save_dataframe(df_labels, paths.annotations_destn, index=False)

## Merge Multiple Anqa Datasets

In [703]:
paths.multi_anqa_fldr

'/home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets'

In [ ]:
df_labels, df_meta = merge_anqua_data(paths.multi_anqa_fldr, save_as_parquet=True, strict=False)

Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_bc-zenodo/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_bc-zenodo/metadata.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_anqa/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_anqa/metadata.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_anqa_samples/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_anqa_samples/metadata.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_raven/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_raven/metadata.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_avianz/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_avianz/metadata.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_freebird_samples/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_freebird_samples/metadata.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_birdclef_samples/annotations.parquet
Loading /home/olly/Desktop/Kaytoo/data/sample_label_formats/small_anqa_datasets/anqa_from_birdclef_samples/metadata.parquet

In [705]:
df_labels.head(3)

,Filename,Start Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),Label,Indv ID,Type,Sex,Score,Life Stage,Delta Time (s),Delta Freq (Hz),Avg Power Density (dB FS/Hz)
0,anqa_from_bc-zenodo/HSN_001_20150708_061805_from_0.flac,3.8,4.0,2272.0,6515.0,gcrfin,NaN,NaN,NaN,NaN,NaN,0.2,4243.0,-77.2
1,anqa_from_bc-zenodo/HSN_001_20150708_061805_from_0.flac,4.6,4.8,2939.0,6303.0,gcrfin,NaN,NaN,NaN,NaN,NaN,0.2,3364.0,-78.8
2,anqa_from_bc-zenodo/HSN_001_20150708_061805_from_0.flac,5.0,5.2,3424.0,4333.0,gcrfin,NaN,NaN,NaN,NaN,NaN,0.2,909.0,-75.0

In [706]:
df_meta.head(3)

,filename,collection,secondary_labels,url,latitude,longitude,author,license,recorded_on,reviewed_by,reviewed_on,source_filename,source_start_s,source_end_s,models_used
0,anqa_from_bc-zenodo/HSN_001_20150708_061805_from_0.flac,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,2015-07-08T06:18:05,Joe Blogs,2025-12-23 09:15:30,HSN_001_20150708_061805.flac,0.0,60.0,['model_1']
1,anqa_from_bc-zenodo/HSN_001_20150708_061805_from_60.flac,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,2015-07-08T06:18:05,Joe Blogs,2025-12-23 09:15:30,HSN_001_20150708_061805.flac,60.0,120.0,['model_1']
2,anqa_from_bc-zenodo/HSN_001_20150708_061805_from_120.flac,birdclef_22,['sidekick_bird'],some_web_address,37.0,-118.5,Mr Bigglesworth,NaN,2015-07-08T06:18:05,Joe Blogs,2025-12-23 09:15:30,HSN_001_20150708_061805.flac,120.0,180.0,['model_1']

In [707]:
dupe_filenames = df_meta[df_meta['filename'].duplicated(keep=False)]
dupe_filenames

Empty DataFrame
Columns: [filename, collection, secondary_labels, url, latitude, longitude, author, license, recorded_on, reviewed_by, reviewed_on, source_filename, source_start_s, source_end_s, models_used]
Index: []

## (Optional) Create `.selections.txt` for Raven
Re-run these cells manually to produce `.selections.txt` files for viewing in [Raven](https://www.ravensoundsoftware.com/)

In [708]:
if config.save_raven_selections:
    anqa_to_raven_selections(df_labels, paths.anqa_destn)  #paths.new_raven_dataset, df_labels
    selections = list(paths.anqa_destn.rglob('*.selections.txt'))
    display(selections[:3])
    random_file = random.choice(selections)
    selection = pd.read_csv(random_file, sep="\t")
    display(selection.head())

In [709]:
config.save_raven_selections = True